### ISSUE TITLE
直接通过运行->运行到小程序模拟器->微信小程序报错

### ISSUE THREAD

**Issue by EMRZZZ** [oyjt/uniapp-vue3-template#17]
C:\project\ToDoEa\uniapp-vue3-template-main\node_modules\.pnpm\cac@6.7.9\node_modules\cac\dist\index.js:404
throw new CACError(`Unknown option \`${name.length > 1 ? `--${name}` : `-${name}`}\``);
^
CACError: Unknown option `--watch`
     at Command.checkUnknownOptions (C:\project\ToDoEa\uniapp-vue3-template-main\node_modules\.pnpm\cac@6.7.9\node_modules\cac\dist\index.js:404:17)
     at CAC.runMatchedCommand (C:\project\ToDoEa\uniapp-vue3-template-main\node_modules\.pnpm\cac@6.7.9\node_modules\cac\dist\index.js:602:13)
     at CAC.parse (C:\project\ToDoEa\uniapp-vue3-template-main\node_modules\.pnpm\cac@6.7.9\node_modules\cac\dist\index.js:541:12)
     at Object.<anonymous> (C:\project\ToDoEa\uniapp-vue3-template-main\node_modules\.pnpm\@dcloudio+vite-plugin-uni@3.0.0-4020420240722002_postcss@8.4.32_rollup@4.17.2_vite@5.2.8_@typ_772wsqyw23ev6csfaz5wocvovq\node_modules\@dcloudio\vite-plugin-uni\dist\cli\index.js:57:5)
     at Module._compile (node:internal/modules/cjs/loader:1358:14)
     at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
     at Module.load (node:internal/modules/cjs/loader:1208:32)
     at Module._load (node:internal/modules/cjs/loader:1024:12)
     at Module.require (node:internal/modules/cjs/loader:1233:19)
     at require (node:internal/modules/helpers:179:18)
 Node.js v20.16.0

**Comment by EMRZZZ** [comment]
通过pnpm dev:mp-weixin后手动导入微信开发者倒是没问题
